### ISSUE TITLE
CreateRequestsSharePointSite function error  "Failed to create the SharePoint site {0} Code: Authorization_RequestDenied Message: Insufficient privileges to complete the operation" v2.0.2

### ISSUE THREAD

**Issue by lhaynes1970** [pnp/provision-assist-m365#109] opened 2024-10-14 09:19 UTC
### Description

Running the deployment script for 2.0.2 results in "Failed to create the SharePoint site {0} Code: Authorization_RequestDenied Message: Insufficient privileges to complete the operation"

This appears for CreateRequestsSharePointSite function

The script actually does create the required Sharepoint site, but it seems that no permissions are applied to it. 
If I browse to the site as the GA that ran the deploy script, I am unable to access it and am asked to request access.

The PNP app reg has the following granted permissions, as per the deployment guide:

Microsoft Graph (2)
Group.Create | Application
Group.Read.All | Application 
SharePoint (1) 
Sites.FullControl.All

PNP shell module logging capture submitted below.
Many thanks:)

### Steps to reproduce

1. Create the PNP app registration.
2. Run the deploy.ps1 script.
3. 

### Expected results

SPO site creation and permissions applied.

### Actual Results

SP Site is created but permissions cannot be applied. Output from PNP shell module log is as follows (real names redacted):

pwsh Error: 0 : 2024-10-14 09:39:10.3018	[PnP.Framework]	[0]	[Error]	Graph call returned the following error: Insufficient privileges to complete the operation..	0ms	
pwsh Error: 0 : 2024-10-14 09:59:05.7690	[PnP.Framework]	[0]	[Error]	ExecuteQuery threw following exception: Microsoft.SharePoint.Client.ServerException: Cannot get site https://<domain>.sharepoint.com/teams/ProvisionAssist.
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)
   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryToServerAsync(ChunkStringBuilder sb)
   at Microsoft.SharePoint.Client.ClientRequest.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientRuntimeContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContext.ExecuteQueryAsync()
   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryImplementation(ClientRuntimeContext clientContext, Int32 retryCount, String userAgent)
ServerErrorCode: -1
ServerErrorTypeName: Microsoft.Online.SharePoint.Common.SpoNoSiteException
ServerErrorTraceCorrelationId: d7c659a1-10b7-a000-2b97-0c6abc17fb46
ServerErrorValue: 
ServerErrorDetails: 
.	0ms	
pwsh Error: 0 : 2024-10-14 09:59:17.3410	[PnP.Framework]	[0]	[Error]	Graph call returned the following error: Insufficient privileges to complete the operation..	0ms

### Solution component

Deployment Script

### Operating system (environment)

Windows

### Additional Info

version 2.0.2 being used here

**Comment by lhaynes1970** [comment] 2024-10-14 09:30
I was running the deploy script again to capture another problem where the script was not handing an existing site correctly (it would fail with an error that states there was an existing site with the same name).

However, the script appears to be running through, but still does not apply any permissions to the GA account that ran the deploy script. When browsing to the site, I am asked to request access.

**Comment by alexc-MSFT** [comment] 2024-10-14 12:36
@lhaynes1970 the deployment script grants permission to the Service Account when creating the site not the account you run the script as.

This will be the Service Account you specify in the parameters.json, this is done by design so that all of the assets pertaining to the solution use (and are owned) by the Service Account.

I'll close this issue but please reopen if you still encounter problems.

Thanks

**Closed by alexc-MSFT** 2024-10-14 12:36 UTC
Labels: bug

**Comment by lhaynes1970** [comment] 2024-10-14 13:00
that makes sense. Apologies, and many thanks for coming back to me
